# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: item.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nitem.proto\"K\n\x0bItemMessage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\nbrand_name\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\x05\x12\x0e\n\x06weight\x18\x04 \x01(\x02\x32\x35\n\x0bItemService\x12&\n\x06\x43reate\x12\x0c.ItemMessage\x1a\x0c.ItemMessage\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'item_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ITEMMESSAGE']._serialized_start=14
  _globals['_ITEMMESSAGE']._serialized_end=89
  _globals['_ITEMSERVICE']._serialized_start=91
  _globals['_ITEMSERVICE']._serialized_end=144
# @@protoc_insertion_point(module_scope)
